### ISSUE TITLE
FFNN

### ISSUE THREAD

**Issue by laika-cosmonaut** [G8LOL/NeuralNetwork#1]
![](https://cdn.discordapp.com/attachments/1091537479854727221/1129224368443105340/watermark.gif)

**Comment by G8LOL** [comment]
quick unblock me

**Comment by laika-cosmonaut** [comment]
why lol

**Comment by CodeByAidan** [comment]
@chaarlottte does NOT fw nn's :(

**Comment by laika-cosmonaut** [comment]
why did u mention me
